import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Farmer, Sale, MechanisationJob, Training, Visit } from '@/types';

// MR Logo as base64 - load from public folder
const MR_LOGO_PATH = '/mrlogo.png';

// Helper to get MR name - fallback if localMrName not provided
const getMrName = (localMrId: string, localMrName?: string) => {
  return localMrName || localMrId || 'Unknown';
};

// Load logo as base64 for PDF
const loadLogoAsBase64 = async (): Promise<string | null> => {
  try {
    const response = await fetch(MR_LOGO_PATH);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

// Generic Excel export
const exportToExcel = <T extends Record<string, any>>(data: T[], filename: string, sheetName: string) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  
  if (data.length > 0) {
    const colWidths = Object.keys(data[0]).map(key => ({
      wch: Math.max(key.length, ...data.map(row => String(row[key] || '').length))
    }));
    worksheet['!cols'] = colWidths;
  }

  XLSX.writeFile(workbook, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

// Generic PDF export with logo
const exportToPDF = async (
  title: string, 
  headers: string[], 
  rows: (string | number)[][], 
  filename: string,
  userName?: string
) => {
  const doc = new jsPDF('landscape');
  const logoBase64 = await loadLogoAsBase64();
  
  // Add logo if available
  let startY = 20;
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', 14, 10, 40, 20);
      startY = 35;
    } catch (e) {
      console.warn('Failed to add logo to PDF:', e);
    }
  }
  
  // Header
  doc.setFontSize(18);
  doc.setTextColor(34, 139, 34);
  doc.text(title, logoBase64 ? 60 : 14, startY);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Total: ${rows.length} records`, logoBase64 ? 60 : 14, startY + 8);
  if (userName) {
    doc.text(`Generated by: ${userName}`, logoBase64 ? 60 : 14, startY + 14);
  }

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: startY + (userName ? 22 : 15),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [34, 139, 34], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('MR Dashboard • Confidential', 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
  }

  doc.save(`${filename}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Farmers Export
export const exportFarmersToExcel = (farmers: Farmer[], filename: string = 'farmers') => {
  const data = farmers.map(farmer => ({
    'Name': farmer.name,
    'Phone': farmer.phone || '',
    'Email': farmer.email || '',
    'Local MR': getMrName(farmer.localMrId || '', farmer.localMrName),
    'County': farmer.location?.county || farmer.county || '',
    'Subcounty': farmer.location?.subcounty || farmer.location?.subCounty || farmer.sub_county || '',
    'Ward': farmer.location?.ward || farmer.ward || '',
    'Village': farmer.location?.village || farmer.village || '',
    'Value Chain': farmer.valueChain || farmer.farming_type || '',
    'Category': farmer.farmerCategory || '',
    'Rating': farmer.farmerRating || '',
    'Trainings Attended': farmer.trainingsAttended || farmer.trainings_attended || 0,
    'Visits Count': farmer.visitsCount || farmer.visits_count || 0,
    'Registration Date': new Date(farmer.createdAt || farmer.created_at || '').toLocaleDateString(),
  }));
  exportToExcel(data, filename, 'Farmers');
};

export const exportFarmersToPDF = async (farmers: Farmer[], filename: string = 'farmers', userName?: string) => {
  const headers = ['Name', 'Phone', 'Local MR', 'Location', 'Value Chain', 'Category', 'Rating', 'Trainings'];
  const rows: (string | number)[][] = farmers.map(farmer => [
    farmer.name,
    farmer.phone || '',
    getMrName(farmer.localMrId || '', farmer.localMrName),
    `${farmer.location?.village || farmer.village || ''}, ${farmer.location?.county || farmer.county || ''}`,
    farmer.valueChain || farmer.farming_type || '',
    farmer.farmerCategory || '',
    farmer.farmerRating || '',
    (farmer.trainingsAttended || farmer.trainings_attended || 0).toString(),
  ]);
  await exportToPDF('Farmers Report', headers, rows, filename, userName);
};

// Sales Export
export const exportSalesToExcel = (sales: Sale[], filename: string = 'sales') => {
  const data = sales.map(sale => ({
    'Date': new Date(sale.date || sale.sale_date || '').toLocaleDateString(),
    'Farmer': sale.farmerName || '',
    'Product': sale.productName || '',
    'Quantity': sale.quantity,
    'Unit Price (KES)': sale.unitPrice || sale.unit_price || 0,
    'Total (KES)': sale.total || sale.total_amount || 0,
    'Commission (KES)': sale.commissionAmount || sale.commission_amount || 0,
    'Status': sale.status || sale.payment_status || '',
    'Recorded By': sale.totName || '',
    'Local MR': sale.localMrName || '',
  }));
  exportToExcel(data, filename, 'Sales');
};

export const exportSalesToPDF = async (sales: Sale[], filename: string = 'sales', userName?: string) => {
  const headers = ['Date', 'Farmer', 'Product', 'Qty', 'Total (KES)', 'Commission', 'Status'];
  const rows: (string | number)[][] = sales.map(sale => [
    new Date(sale.date || sale.sale_date || '').toLocaleDateString(),
    sale.farmerName ?? '',
    sale.productName ?? '',
    sale.quantity,
    (sale.total || sale.total_amount || 0).toLocaleString(),
    (sale.commissionAmount || sale.commission_amount || 0).toLocaleString(),
    sale.status || sale.payment_status || '',
  ]);
  await exportToPDF('Sales Report', headers, rows, filename, userName);
};

// Mechanisation Export
export const exportMechanisationToExcel = (jobs: MechanisationJob[], filename: string = 'mechanisation') => {
  const data = jobs.map(job => ({
    'Farmer': job.farmerName || '',
    'Service Type': job.serviceType || job.service_type || '',
    'Machinery': job.machineryName || '',
    'Acreage': job.acreage || job.area_acres || 0,
    'Total (KES)': job.totalPrice || job.total_cost || 0,
    'Commission (KES)': job.commissionAmount || 0,
    'Scheduled Date': new Date(job.scheduledDate || job.scheduled_date || '').toLocaleDateString(),
    'Status': job.status,
    'Booked By': job.bookedByName || '',
    'Local MR': job.localMrName || '',
  }));
  exportToExcel(data, filename, 'Mechanisation');
};

export const exportMechanisationToPDF = async (jobs: MechanisationJob[], filename: string = 'mechanisation', userName?: string) => {
  const headers = ['Farmer', 'Service', 'Machinery', 'Acres', 'Total (KES)', 'Status', 'Date'];
  const rows: (string | number)[][] = jobs.map(job => [
    job.farmerName ?? '',
    job.serviceType || job.service_type || '',
    job.machineryName ?? '',
    job.acreage || job.area_acres || 0,
    (job.totalPrice || job.total_cost || 0).toLocaleString(),
    job.status,
    new Date(job.scheduledDate || job.scheduled_date || '').toLocaleDateString(),
  ]);
  await exportToPDF('Mechanisation Report', headers, rows, filename, userName);
};

// Trainings Export
export const exportTrainingsToExcel = (trainings: Training[], filename: string = 'trainings') => {
  const data = trainings.map(training => ({
    'Title': training.title,
    'Type': training.type || training.training_type || '',
    'Date': new Date(training.date || training.scheduled_date || '').toLocaleDateString(),
    'Location': training.location || training.venue || '',
    'Duration (hrs)': training.duration || training.duration_hours || 0,
    'Trainer': training.trainerName || '',
    'Attendees': training.attendees?.length || 0,
    'Topics': (training.topics || []).join(', '),
    'Status': training.status,
    'Local MR': training.localMrName || '',
  }));
  exportToExcel(data, filename, 'Trainings');
};

export const exportTrainingsToPDF = async (trainings: Training[], filename: string = 'trainings', userName?: string) => {
  const headers = ['Title', 'Type', 'Date', 'Location', 'Duration', 'Trainer', 'Attendees'];
  const rows: (string | number)[][] = trainings.map(training => [
    training.title,
    training.type || training.training_type || '',
    new Date(training.date || training.scheduled_date || '').toLocaleDateString(),
    training.location || training.venue || '',
    `${training.duration || training.duration_hours || 0} hrs`,
    training.trainerName ?? '',
    (training.attendees?.length || 0).toString(),
  ]);
  await exportToPDF('Trainings Report', headers, rows, filename, userName);
};

// Visits Export
export const exportVisitsToExcel = (visits: Visit[], filename: string = 'visits') => {
  const data = visits.map(visit => ({
    'Farmer': visit.farmerName || '',
    'Purpose': visit.purpose,
    'Date': new Date(visit.date || visit.visit_date || '').toLocaleDateString(),
    'Notes': visit.notes || '',
    'Recorded By': visit.totName || '',
    'Local MR': visit.localMrName || '',
    'Follow-up Required': visit.follow_up_required ? 'Yes' : 'No',
    'Follow-up Date': visit.follow_up_date ? new Date(visit.follow_up_date).toLocaleDateString() : '',
  }));
  exportToExcel(data, filename, 'Visits');
};

export const exportVisitsToPDF = async (visits: Visit[], filename: string = 'visits', userName?: string) => {
  const headers = ['Farmer', 'Purpose', 'Date', 'Notes', 'Recorded By', 'Follow-up'];
  const rows: (string | number)[][] = visits.map(visit => {
    const notes = visit.notes || '';
    return [
      visit.farmerName ?? '',
      visit.purpose,
      new Date(visit.date || visit.visit_date || '').toLocaleDateString(),
      notes.substring(0, 50) + (notes.length > 50 ? '...' : ''),
      visit.totName ?? '',
      visit.follow_up_required ? 'Yes' : 'No',
    ];
  });
  await exportToPDF('Visits Report', headers, rows, filename, userName);
};

// Commission Report Export
export interface CommissionData {
  totName: string;
  localMrName: string;
  salesCount: number;
  totalSales: number;
  totalCommission: number;
  paidCommission: number;
  pendingCommission: number;
}

export const exportCommissionToExcel = (data: CommissionData[], filename: string = 'commission') => {
  const exportData = data.map(item => ({
    'TOT Name': item.totName,
    'Local MR': item.localMrName,
    'Sales Count': item.salesCount,
    'Total Sales (KES)': item.totalSales,
    'Total Commission (KES)': item.totalCommission,
    'Paid Commission (KES)': item.paidCommission,
    'Pending Commission (KES)': item.pendingCommission,
  }));
  exportToExcel(exportData, filename, 'Commission');
};

export const exportCommissionToPDF = async (data: CommissionData[], filename: string = 'commission', userName?: string) => {
  const headers = ['TOT Name', 'Local MR', 'Sales', 'Total Sales', 'Commission', 'Paid', 'Pending'];
  const rows: (string | number)[][] = data.map(item => [
    item.totName,
    item.localMrName,
    item.salesCount,
    item.totalSales.toLocaleString(),
    item.totalCommission.toLocaleString(),
    item.paidCommission.toLocaleString(),
    item.pendingCommission.toLocaleString(),
  ]);
  await exportToPDF('Commission Report', headers, rows, filename, userName);
};

// Performance Report Export
export interface PerformanceData {
  name: string;
  localMrName: string;
  farmersServed: number;
  totalSales: number;
  totalRevenue: number;
  mechanisationJobs: number;
  trainingsHeld: number;
  visitsLogged: number;
}

export const exportPerformanceToExcel = (data: PerformanceData[], filename: string = 'performance') => {
  const exportData = data.map(item => ({
    'Name': item.name,
    'Local MR': item.localMrName,
    'Farmers Served': item.farmersServed,
    'Total Sales': item.totalSales,
    'Revenue (KES)': item.totalRevenue,
    'Mechanisation Jobs': item.mechanisationJobs,
    'Trainings Held': item.trainingsHeld,
    'Visits Logged': item.visitsLogged,
  }));
  exportToExcel(exportData, filename, 'Performance');
};

export const exportPerformanceToPDF = async (data: PerformanceData[], filename: string = 'performance', userName?: string) => {
  const headers = ['Name', 'Local MR', 'Farmers', 'Sales', 'Revenue', 'Mech Jobs', 'Trainings', 'Visits'];
  const rows: (string | number)[][] = data.map(item => [
    item.name,
    item.localMrName,
    item.farmersServed,
    item.totalSales,
    item.totalRevenue.toLocaleString(),
    item.mechanisationJobs,
    item.trainingsHeld,
    item.visitsLogged,
  ]);
  await exportToPDF('Performance Report', headers, rows, filename, userName);
};
