import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Farmer, Sale, MechanisationJob, Training, Visit } from '@/types';
import {
  renderSalesBarChart,
  renderPieChart,
  renderLineChart,
  renderHorizontalBarChart,
  renderSummaryCard,
  ChartDataItem,
} from './pdfChartUtils';

// MR Logo path
const MR_LOGO_PATH = '/mrlogo.png';

// Helper to get MR name
const getMrName = (localMrId: string, localMrName?: string) => {
  return localMrName || localMrId || 'Unknown';
};

// Load logo as base64 for PDF
const loadLogoAsBase64 = async (): Promise<string | null> => {
  try {
    const response = await fetch(MR_LOGO_PATH);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

// Add chart image to PDF
const addChartToPDF = (
  doc: jsPDF,
  chartBase64: string | null,
  x: number,
  y: number,
  width: number,
  height: number
): number => {
  if (chartBase64) {
    try {
      doc.addImage(chartBase64, 'PNG', x, y, width, height);
      return y + height + 10;
    } catch (e) {
      console.warn('Failed to add chart to PDF:', e);
    }
  }
  return y;
};

// Generic Excel export
const exportToExcel = <T extends Record<string, any>>(data: T[], filename: string, sheetName: string) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  
  if (data.length > 0) {
    const colWidths = Object.keys(data[0]).map(key => ({
      wch: Math.max(key.length, ...data.map(row => String(row[key] || '').length))
    }));
    worksheet['!cols'] = colWidths;
  }

  XLSX.writeFile(workbook, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

// Enhanced PDF export with charts
interface PDFExportOptions {
  title: string;
  headers: string[];
  rows: (string | number)[][];
  filename: string;
  userName?: string;
  charts?: {
    type: 'bar' | 'pie' | 'line' | 'horizontal-bar' | 'summary';
    data: ChartDataItem[] | { label: string; value: string | number }[];
    title: string;
    dataKeys?: string[];
  }[];
  summaryStats?: { label: string; value: string | number }[];
}

const exportToPDFWithCharts = async (options: PDFExportOptions) => {
  const { title, headers, rows, filename, userName, charts = [], summaryStats } = options;
  const doc = new jsPDF('landscape');
  const logoBase64 = await loadLogoAsBase64();
  
  // Page 1: Header with logo and summary
  let currentY = 15;
  
  // Add logo
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', 14, 10, 35, 18);
      currentY = 32;
    } catch (e) {
      console.warn('Failed to add logo:', e);
    }
  }
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(34, 139, 34);
  doc.text(title, logoBase64 ? 55 : 14, currentY);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Total Records: ${rows.length}`, logoBase64 ? 55 : 14, currentY + 8);
  if (userName) {
    doc.text(`Generated by: ${userName}`, logoBase64 ? 55 : 14, currentY + 14);
  }
  
  currentY += userName ? 25 : 18;
  
  // Add summary stats card if provided
  if (summaryStats && summaryStats.length > 0) {
    const summaryChart = await renderSummaryCard(summaryStats, 'Report Summary');
    currentY = addChartToPDF(doc, summaryChart, 14, currentY, 180, 40);
  }
  
  // Add charts
  let chartX = 14;
  let chartRowY = currentY;
  
  for (let i = 0; i < charts.length; i++) {
    const chart = charts[i];
    let chartImage: string | null = null;
    
    switch (chart.type) {
      case 'bar':
        chartImage = await renderSalesBarChart(chart.data as ChartDataItem[]);
        break;
      case 'pie':
        chartImage = await renderPieChart(chart.data as ChartDataItem[], chart.title);
        break;
      case 'line':
        chartImage = await renderLineChart(chart.data as ChartDataItem[], chart.title, chart.dataKeys);
        break;
      case 'horizontal-bar':
        chartImage = await renderHorizontalBarChart(chart.data as ChartDataItem[], chart.title);
        break;
    }
    
    if (chartImage) {
      const chartWidth = chart.type === 'pie' ? 130 : 140;
      const chartHeight = 80;
      
      // Check if we need a new row
      if (chartX + chartWidth > 280) {
        chartX = 14;
        chartRowY += chartHeight + 5;
      }
      
      // Check if we need a new page
      if (chartRowY + chartHeight > 190) {
        doc.addPage();
        chartRowY = 20;
        chartX = 14;
      }
      
      addChartToPDF(doc, chartImage, chartX, chartRowY, chartWidth, chartHeight);
      chartX += chartWidth + 5;
    }
  }
  
  // Add new page for data table
  doc.addPage();
  
  // Data table
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 20,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [34, 139, 34], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 14, right: 14 },
  });

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('MR Dashboard - Confidential', 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 35, doc.internal.pageSize.height - 10);
  }

  doc.save(`${filename}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Simple PDF export (fallback)
const exportToPDFSimple = async (
  title: string, 
  headers: string[], 
  rows: (string | number)[][], 
  filename: string,
  userName?: string
) => {
  const doc = new jsPDF('landscape');
  const logoBase64 = await loadLogoAsBase64();
  
  let startY = 20;
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', 14, 10, 40, 20);
      startY = 35;
    } catch (e) {
      console.warn('Failed to add logo:', e);
    }
  }
  
  doc.setFontSize(18);
  doc.setTextColor(34, 139, 34);
  doc.text(title, logoBase64 ? 60 : 14, startY);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Total: ${rows.length} records`, logoBase64 ? 60 : 14, startY + 8);
  if (userName) {
    doc.text(`Generated by: ${userName}`, logoBase64 ? 60 : 14, startY + 14);
  }

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: startY + (userName ? 22 : 15),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [34, 139, 34], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 14, right: 14 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('MR Dashboard - Confidential', 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
  }

  doc.save(`${filename}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// ==================== FARMERS ====================
export const exportFarmersToExcel = (farmers: Farmer[], filename: string = 'farmers') => {
  const data = farmers.map(farmer => ({
    'Name': farmer.name,
    'Phone': farmer.phone || '',
    'Email': farmer.email || '',
    'Local MR': getMrName(farmer.localMrId || '', farmer.localMrName),
    'County': farmer.location?.county || farmer.county || '',
    'Subcounty': farmer.location?.subcounty || farmer.location?.subCounty || farmer.sub_county || '',
    'Ward': farmer.location?.ward || farmer.ward || '',
    'Village': farmer.location?.village || farmer.village || '',
    'Value Chain': farmer.valueChain || farmer.farming_type || '',
    'Category': farmer.farmerCategory || '',
    'Rating': farmer.farmerRating || '',
    'Trainings Attended': farmer.trainingsAttended || farmer.trainings_attended || 0,
    'Visits Count': farmer.visitsCount || farmer.visits_count || 0,
    'Registration Date': new Date(farmer.createdAt || farmer.created_at || '').toLocaleDateString(),
  }));
  exportToExcel(data, filename, 'Farmers');
};

export const exportFarmersToPDF = async (farmers: Farmer[], filename: string = 'farmers', userName?: string) => {
  const headers = ['Name', 'Phone', 'Local MR', 'Location', 'Value Chain', 'Category', 'Rating', 'Trainings'];
  const rows: (string | number)[][] = farmers.map(farmer => [
    farmer.name,
    farmer.phone || '',
    getMrName(farmer.localMrId || '', farmer.localMrName),
    `${farmer.location?.village || farmer.village || ''}, ${farmer.location?.county || farmer.county || ''}`,
    farmer.valueChain || farmer.farming_type || '',
    farmer.farmerCategory || '',
    farmer.farmerRating || '',
    (farmer.trainingsAttended || farmer.trainings_attended || 0).toString(),
  ]);

  // Prepare chart data
  const countyData: Record<string, number> = {};
  const valueChainData: Record<string, number> = {};
  const categoryData: Record<string, number> = {};
  
  farmers.forEach(f => {
    const county = f.location?.county || f.county || 'Unknown';
    const valueChain = f.valueChain || f.farming_type || 'Unknown';
    const category = f.farmerCategory || 'Unknown';
    
    countyData[county] = (countyData[county] || 0) + 1;
    valueChainData[valueChain] = (valueChainData[valueChain] || 0) + 1;
    categoryData[category] = (categoryData[category] || 0) + 1;
  });

  const countyChartData: ChartDataItem[] = Object.entries(countyData)
    .map(([name, value]) => ({ name, value }))
    .sort((a, b) => b.value - a.value);
  
  const valueChainChartData: ChartDataItem[] = Object.entries(valueChainData)
    .map(([name, value]) => ({ name, value }))
    .sort((a, b) => b.value - a.value);

  await exportToPDFWithCharts({
    title: 'Farmers Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'Total Farmers', value: farmers.length },
      { label: 'Counties', value: Object.keys(countyData).length },
      { label: 'Value Chains', value: Object.keys(valueChainData).length },
      { label: 'Active', value: farmers.filter(f => f.farmerRating === 'Active' || f.status === 'active').length },
    ],
    charts: [
      { type: 'pie', data: valueChainChartData, title: 'Farmers by Value Chain' },
      { type: 'horizontal-bar', data: countyChartData, title: 'Farmers by County' },
    ],
  });
};

// ==================== SALES ====================
export const exportSalesToExcel = (sales: Sale[], filename: string = 'sales') => {
  const data = sales.map(sale => ({
    'Date': new Date(sale.date || sale.sale_date || '').toLocaleDateString(),
    'Farmer': sale.farmerName || '',
    'Product': sale.productName || '',
    'Quantity': sale.quantity,
    'Unit Price (KES)': sale.unitPrice || sale.unit_price || 0,
    'Total (KES)': sale.total || sale.total_amount || 0,
    'Commission (KES)': sale.commissionAmount || sale.commission_amount || 0,
    'Status': sale.status || sale.payment_status || '',
    'Recorded By': sale.totName || '',
    'Local MR': sale.localMrName || '',
  }));
  exportToExcel(data, filename, 'Sales');
};

export const exportSalesToPDF = async (sales: Sale[], filename: string = 'sales', userName?: string) => {
  const headers = ['Date', 'Farmer', 'Product', 'Qty', 'Total (KES)', 'Commission', 'Status'];
  const rows: (string | number)[][] = sales.map(sale => [
    new Date(sale.date || sale.sale_date || '').toLocaleDateString(),
    sale.farmerName ?? '',
    sale.productName ?? '',
    sale.quantity,
    (sale.total || sale.total_amount || 0).toLocaleString(),
    (sale.commissionAmount || sale.commission_amount || 0).toLocaleString(),
    sale.status || sale.payment_status || '',
  ]);

  // Prepare chart data
  const productData: Record<string, number> = {};
  const monthlyData: Record<string, { sales: number; revenue: number }> = {};
  
  sales.forEach(s => {
    const product = s.productName || 'Unknown';
    const total = s.total || s.total_amount || 0;
    productData[product] = (productData[product] || 0) + total;
    
    const date = new Date(s.date || s.sale_date || '');
    const month = date.toLocaleDateString('en-US', { month: 'short', year: '2-digit' });
    if (!monthlyData[month]) monthlyData[month] = { sales: 0, revenue: 0 };
    monthlyData[month].sales += 1;
    monthlyData[month].revenue += total;
  });

  const productChartData: ChartDataItem[] = Object.entries(productData)
    .map(([name, value]) => ({ name, value }))
    .sort((a, b) => b.value - a.value);

  const monthlyChartData: ChartDataItem[] = Object.entries(monthlyData)
    .map(([name, data]) => ({ name, value: data.revenue, sales: data.sales }))
    .slice(-12);

  const totalRevenue = sales.reduce((sum, s) => sum + (s.total || s.total_amount || 0), 0);
  const totalCommission = sales.reduce((sum, s) => sum + (s.commissionAmount || s.commission_amount || 0), 0);

  await exportToPDFWithCharts({
    title: 'Sales Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'Total Sales', value: sales.length },
      { label: 'Revenue', value: `KES ${(totalRevenue / 1000).toFixed(0)}K` },
      { label: 'Commission', value: `KES ${(totalCommission / 1000).toFixed(0)}K` },
      { label: 'Products', value: Object.keys(productData).length },
    ],
    charts: [
      { type: 'bar', data: productChartData, title: 'Revenue by Product' },
      { type: 'line', data: monthlyChartData, title: 'Monthly Trend', dataKeys: ['value'] },
    ],
  });
};

// ==================== MECHANISATION ====================
export const exportMechanisationToExcel = (jobs: MechanisationJob[], filename: string = 'mechanisation') => {
  const data = jobs.map(job => ({
    'Farmer': job.farmerName || '',
    'Service Type': job.serviceType || job.service_type || '',
    'Machinery': job.machineryName || '',
    'Acreage': job.acreage || job.area_acres || 0,
    'Total (KES)': job.totalPrice || job.total_cost || 0,
    'Commission (KES)': job.commissionAmount || 0,
    'Scheduled Date': new Date(job.scheduledDate || job.scheduled_date || '').toLocaleDateString(),
    'Status': job.status,
    'Booked By': job.bookedByName || '',
    'Local MR': job.localMrName || '',
  }));
  exportToExcel(data, filename, 'Mechanisation');
};

export const exportMechanisationToPDF = async (jobs: MechanisationJob[], filename: string = 'mechanisation', userName?: string) => {
  const headers = ['Farmer', 'Service', 'Machinery', 'Acres', 'Total (KES)', 'Status', 'Date'];
  const rows: (string | number)[][] = jobs.map(job => [
    job.farmerName ?? '',
    job.serviceType || job.service_type || '',
    job.machineryName ?? '',
    job.acreage || job.area_acres || 0,
    (job.totalPrice || job.total_cost || 0).toLocaleString(),
    job.status,
    new Date(job.scheduledDate || job.scheduled_date || '').toLocaleDateString(),
  ]);

  // Prepare chart data
  const serviceData: Record<string, number> = {};
  const statusData: Record<string, number> = {};
  
  jobs.forEach(j => {
    const service = j.serviceType || j.service_type || 'Unknown';
    const status = j.status || 'Unknown';
    serviceData[service] = (serviceData[service] || 0) + 1;
    statusData[status] = (statusData[status] || 0) + 1;
  });

  const serviceChartData: ChartDataItem[] = Object.entries(serviceData)
    .map(([name, value]) => ({ name, value }));
  
  const statusChartData: ChartDataItem[] = Object.entries(statusData)
    .map(([name, value]) => ({ name, value }));

  const totalAcres = jobs.reduce((sum, j) => sum + (j.acreage || j.area_acres || 0), 0);
  const totalRevenue = jobs.reduce((sum, j) => sum + (j.totalPrice || j.total_cost || 0), 0);

  await exportToPDFWithCharts({
    title: 'Mechanisation Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'Total Jobs', value: jobs.length },
      { label: 'Total Acres', value: totalAcres.toFixed(1) },
      { label: 'Revenue', value: `KES ${(totalRevenue / 1000).toFixed(0)}K` },
      { label: 'Completed', value: jobs.filter(j => j.status === 'completed').length },
    ],
    charts: [
      { type: 'pie', data: serviceChartData, title: 'Jobs by Service Type' },
      { type: 'pie', data: statusChartData, title: 'Jobs by Status' },
    ],
  });
};

// ==================== TRAININGS ====================
export const exportTrainingsToExcel = (trainings: Training[], filename: string = 'trainings') => {
  const data = trainings.map(training => ({
    'Title': training.title,
    'Type': training.type || training.training_type || '',
    'Date': new Date(training.date || training.scheduled_date || '').toLocaleDateString(),
    'Location': training.location || training.venue || '',
    'Duration (hrs)': training.duration || training.duration_hours || 0,
    'Trainer': training.trainerName || '',
    'Attendees': training.attendees?.length || 0,
    'Topics': (training.topics || []).join(', '),
    'Status': training.status,
    'Local MR': training.localMrName || '',
  }));
  exportToExcel(data, filename, 'Trainings');
};

export const exportTrainingsToPDF = async (trainings: Training[], filename: string = 'trainings', userName?: string) => {
  const headers = ['Title', 'Type', 'Date', 'Location', 'Duration', 'Trainer', 'Attendees'];
  const rows: (string | number)[][] = trainings.map(training => [
    training.title,
    training.type || training.training_type || '',
    new Date(training.date || training.scheduled_date || '').toLocaleDateString(),
    training.location || training.venue || '',
    `${training.duration || training.duration_hours || 0} hrs`,
    training.trainerName ?? '',
    (training.attendees?.length || 0).toString(),
  ]);

  // Prepare chart data
  const typeData: Record<string, number> = {};
  const statusData: Record<string, number> = {};
  
  trainings.forEach(t => {
    const type = t.type || t.training_type || 'Unknown';
    const status = t.status || 'Unknown';
    typeData[type] = (typeData[type] || 0) + 1;
    statusData[status] = (statusData[status] || 0) + 1;
  });

  const typeChartData: ChartDataItem[] = Object.entries(typeData)
    .map(([name, value]) => ({ name, value }));

  const totalAttendees = trainings.reduce((sum, t) => sum + (t.attendees?.length || 0), 0);
  const totalHours = trainings.reduce((sum, t) => sum + (t.duration || t.duration_hours || 0), 0);

  await exportToPDFWithCharts({
    title: 'Trainings Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'Total Trainings', value: trainings.length },
      { label: 'Total Attendees', value: totalAttendees },
      { label: 'Total Hours', value: totalHours },
      { label: 'Completed', value: trainings.filter(t => t.status?.toLowerCase() === 'completed').length },
    ],
    charts: [
      { type: 'pie', data: typeChartData, title: 'Trainings by Type' },
    ],
  });
};

// ==================== VISITS ====================
export const exportVisitsToExcel = (visits: Visit[], filename: string = 'visits') => {
  const data = visits.map(visit => ({
    'Farmer': visit.farmerName || '',
    'Purpose': visit.purpose,
    'Date': new Date(visit.date || visit.visit_date || '').toLocaleDateString(),
    'Notes': visit.notes || '',
    'Recorded By': visit.totName || '',
    'Local MR': visit.localMrName || '',
    'Follow-up Required': visit.follow_up_required ? 'Yes' : 'No',
    'Follow-up Date': visit.follow_up_date ? new Date(visit.follow_up_date).toLocaleDateString() : '',
  }));
  exportToExcel(data, filename, 'Visits');
};

export const exportVisitsToPDF = async (visits: Visit[], filename: string = 'visits', userName?: string) => {
  const headers = ['Farmer', 'Purpose', 'Date', 'Notes', 'Recorded By', 'Follow-up'];
  const rows: (string | number)[][] = visits.map(visit => {
    const notes = visit.notes || '';
    return [
      visit.farmerName ?? '',
      visit.purpose,
      new Date(visit.date || visit.visit_date || '').toLocaleDateString(),
      notes.substring(0, 50) + (notes.length > 50 ? '...' : ''),
      visit.totName ?? '',
      visit.follow_up_required ? 'Yes' : 'No',
    ];
  });

  // Prepare chart data
  const purposeData: Record<string, number> = {};
  
  visits.forEach(v => {
    const purpose = v.purpose || 'Unknown';
    purposeData[purpose] = (purposeData[purpose] || 0) + 1;
  });

  const purposeChartData: ChartDataItem[] = Object.entries(purposeData)
    .map(([name, value]) => ({ name, value }))
    .sort((a, b) => b.value - a.value);

  await exportToPDFWithCharts({
    title: 'Visits Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'Total Visits', value: visits.length },
      { label: 'Follow-ups', value: visits.filter(v => v.follow_up_required).length },
      { label: 'Purposes', value: Object.keys(purposeData).length },
    ],
    charts: [
      { type: 'horizontal-bar', data: purposeChartData, title: 'Visits by Purpose' },
    ],
  });
};

// ==================== COMMISSION ====================
export interface CommissionData {
  totName: string;
  localMrName: string;
  salesCount: number;
  totalSales: number;
  totalCommission: number;
  paidCommission: number;
  pendingCommission: number;
}

export const exportCommissionToExcel = (data: CommissionData[], filename: string = 'commission') => {
  const exportData = data.map(item => ({
    'TOT Name': item.totName,
    'Local MR': item.localMrName,
    'Sales Count': item.salesCount,
    'Total Sales (KES)': item.totalSales,
    'Total Commission (KES)': item.totalCommission,
    'Paid Commission (KES)': item.paidCommission,
    'Pending Commission (KES)': item.pendingCommission,
  }));
  exportToExcel(exportData, filename, 'Commission');
};

export const exportCommissionToPDF = async (data: CommissionData[], filename: string = 'commission', userName?: string) => {
  const headers = ['TOT Name', 'Local MR', 'Sales', 'Total Sales', 'Commission', 'Paid', 'Pending'];
  const rows: (string | number)[][] = data.map(item => [
    item.totName,
    item.localMrName,
    item.salesCount,
    item.totalSales.toLocaleString(),
    item.totalCommission.toLocaleString(),
    item.paidCommission.toLocaleString(),
    item.pendingCommission.toLocaleString(),
  ]);

  const commissionChartData: ChartDataItem[] = data
    .map(d => ({ name: d.totName, value: d.totalCommission }))
    .sort((a, b) => b.value - a.value);

  const totalCommission = data.reduce((sum, d) => sum + d.totalCommission, 0);
  const totalPaid = data.reduce((sum, d) => sum + d.paidCommission, 0);
  const totalPending = data.reduce((sum, d) => sum + d.pendingCommission, 0);

  await exportToPDFWithCharts({
    title: 'Commission Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'TOTs', value: data.length },
      { label: 'Total Commission', value: `KES ${(totalCommission / 1000).toFixed(0)}K` },
      { label: 'Paid', value: `KES ${(totalPaid / 1000).toFixed(0)}K` },
      { label: 'Pending', value: `KES ${(totalPending / 1000).toFixed(0)}K` },
    ],
    charts: [
      { type: 'horizontal-bar', data: commissionChartData, title: 'Commission by TOT' },
    ],
  });
};

// ==================== PERFORMANCE ====================
export interface PerformanceData {
  name: string;
  localMrName: string;
  farmersServed: number;
  totalSales: number;
  totalRevenue: number;
  mechanisationJobs: number;
  trainingsHeld: number;
  visitsLogged: number;
}

export const exportPerformanceToExcel = (data: PerformanceData[], filename: string = 'performance') => {
  const exportData = data.map(item => ({
    'Name': item.name,
    'Local MR': item.localMrName,
    'Farmers Served': item.farmersServed,
    'Total Sales': item.totalSales,
    'Revenue (KES)': item.totalRevenue,
    'Mechanisation Jobs': item.mechanisationJobs,
    'Trainings Held': item.trainingsHeld,
    'Visits Logged': item.visitsLogged,
  }));
  exportToExcel(exportData, filename, 'Performance');
};

export const exportPerformanceToPDF = async (data: PerformanceData[], filename: string = 'performance', userName?: string) => {
  const headers = ['Name', 'Local MR', 'Farmers', 'Sales', 'Revenue', 'Mech Jobs', 'Trainings', 'Visits'];
  const rows: (string | number)[][] = data.map(item => [
    item.name,
    item.localMrName,
    item.farmersServed,
    item.totalSales,
    item.totalRevenue.toLocaleString(),
    item.mechanisationJobs,
    item.trainingsHeld,
    item.visitsLogged,
  ]);

  const revenueChartData: ChartDataItem[] = data
    .map(d => ({ name: d.name, value: d.totalRevenue }))
    .sort((a, b) => b.value - a.value);

  const salesChartData: ChartDataItem[] = data
    .map(d => ({ name: d.name, value: d.totalSales }))
    .sort((a, b) => b.value - a.value);

  const totalRevenue = data.reduce((sum, d) => sum + d.totalRevenue, 0);
  const totalSales = data.reduce((sum, d) => sum + d.totalSales, 0);

  await exportToPDFWithCharts({
    title: 'Performance Report',
    headers,
    rows,
    filename,
    userName,
    summaryStats: [
      { label: 'TOTs', value: data.length },
      { label: 'Total Sales', value: totalSales },
      { label: 'Revenue', value: `KES ${(totalRevenue / 1000).toFixed(0)}K` },
    ],
    charts: [
      { type: 'horizontal-bar', data: revenueChartData, title: 'Revenue by TOT' },
      { type: 'bar', data: salesChartData, title: 'Sales Count by TOT' },
    ],
  });
};
