project_id = "zdykomfdrpfwitdrbhuk"

[functions.bootstrap-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.purge-user-by-email]
verify_jwt = false
