// src/components/reports/Reports.tsx (or wherever your file is)
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  FileText, 
  Download, 
  Users, 
  ShoppingCart, 
  Tractor, 
  GraduationCap, 
  TrendingUp,
  Calendar,
  Building2
} from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { jsPDF } from 'jspdf';
import { utils, writeFile } from 'xlsx';
import { format } from 'date-fns';

const reportTypes = [
  {
    id: 'sales',
    title: 'Sales Report',
    description: 'Sales transactions, revenue, and commissions',
    icon: ShoppingCart,
    color: 'forest',
  },
  {
    id: 'farmers',
    title: 'Farmer Profiles',
    description: 'Farmer registry with contact details',
    icon: Users,
    color: 'wheat',
  },
  {
    id: 'mechanisation',
    title: 'Mechanisation Report',
    description: 'Machinery service bookings summary',
    icon: Tractor,
    color: 'earth',
  },
  {
    id: 'trainings',
    title: 'Training Report',
    description: 'Capacity building and attendance',
    icon: GraduationCap,
    color: 'forest',
  },
  {
    id: 'performance',
    title: 'Performance Report',
    description: 'TOT metrics and targets achieved',
    icon: TrendingUp,
    color: 'wheat',
  },
  {
    id: 'commission',
    title: 'Commission Report',
    description: 'Commission earnings breakdown',
    icon: FileText,
    color: 'earth',
  },
];

const managerReports = [
  {
    id: 'branch',
    title: 'Branch Performance',
    description: 'Branch-level analytics',
    icon: Building2,
    color: 'forest',
  },
  {
    id: 'tot-comparison',
    title: 'TOT Comparison',
    description: 'Compare all TOTs in branch',
    icon: Users,
    color: 'wheat',
  },
];

export function Reports() {
  const { user } = useAuth();

  const allReports = user?.role === 'manager' || user?.role === 'admin' 
    ? [...reportTypes, ...managerReports] 
    : reportTypes;

  const currentMonth = format(new Date(), 'MMMM yyyy'); // e.g., "December 2025"

  const getColorClass = (color: string) => {
    switch (color) {
      case 'forest': return 'bg-primary text-primary-foreground';
      case 'wheat': return 'bg-accent text-accent-foreground';
      case 'earth': return 'bg-secondary text-secondary-foreground';
      default: return 'bg-muted text-foreground';
    }
  };

  // Sample real-looking data (replace with actual API fetch later)
  const sampleData = [
    { id: 1, name: 'John Kamau', product: 'Fertilizer', amount: 12500, date: '2025-12-15' },
    { id: 2, name: 'Mary Wanjiku', product: 'Seeds', amount: 8900, date: '2025-12-18' },
    { id: 3, name: 'Peter Otieno', product: 'Mechanisation', amount: 45000, date: '2025-12-20' },
  ];

  const exportToPDF = (reportTitle: string) => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text(`${reportTitle} - ${currentMonth}`, 20, 20);
    doc.setFontSize(12);
    doc.text('Generated on: ' + format(new Date(), 'PPP'), 20, 30);
    doc.text('Generated by: ' + (user?.name || 'System'), 20, 40);

    // Simple table
    let y = 60;
    doc.text('Sample Data Entries:', 20, y);
    y += 10;
    sampleData.forEach((row, i) => {
      doc.text(`${i + 1}. ${row.name} - ${row.product} - KES ${row.amount.toLocaleString()}`, 30, y);
      y += 10;
    });

    doc.save(`${reportTitle.replace(/\s+/g, '_')}_${currentMonth}.pdf`);
  };

  const exportToExcel = (reportTitle: string) => {
    const ws = utils.json_to_sheet(sampleData.map(row => ({
      Name: row.name,
      Product: row.product,
      Amount: row.amount,
      Date: row.date,
    })));

    const wb = utils.book_new();
    utils.book_append_sheet(wb, ws, 'Report');
    writeFile(wb, `${reportTitle.replace(/\s+/g, '_')}_${currentMonth}.xlsx`);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
        <div>
          <h1 className="font-heading text-xl sm:text-2xl font-bold text-foreground">Reports</h1>
          <p className="text-sm text-muted-foreground">Generate and export reports in PDF or Excel</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" disabled>
            <Calendar className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Select </span>Date Range
          </Button>
        </div>
      </div>

      {/* Monthly Summary - Now dynamic (no mock numbers) */}
      <Card variant="gradient" className="p-4 sm:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h3 className="font-heading text-base sm:text-lg font-semibold mb-1">Monthly Summary</h3>
            <p className="text-xs sm:text-sm opacity-80">{currentMonth} overview</p>
          </div>
          <div className="text-sm text-muted-foreground italic">
            Connect data sources to view live metrics
          </div>
        </div>
      </Card>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4">
        {allReports.map((report, index) => (
          <Card 
            key={report.id}
            variant="elevated"
            className="animate-fade-in"
            style={{ animationDelay: `${index * 0.05}s` }}
          >
            <CardHeader className="pb-2 p-4 sm:p-6 sm:pb-2">
              <div className="flex items-start justify-between gap-2">
                <div className={`w-10 h-10 sm:w-12 sm:h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${getColorClass(report.color)}`}>
                  <report.icon className="w-5 h-5 sm:w-6 sm:h-6" />
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">PDF</Badge>
                  <Badge variant="outline" className="text-xs">Excel</Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-4 sm:p-6 pt-2 sm:pt-2">
              <CardTitle className="text-sm sm:text-lg mb-1">{report.title}</CardTitle>
              <CardDescription className="text-xs sm:text-sm mb-3 sm:mb-4 line-clamp-2">
                {report.description}
              </CardDescription>
              <div className="flex gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="flex-1 text-xs h-8 sm:h-9"
                  onClick={() => exportToPDF(report.title)}
                >
                  <Download className="w-3.5 h-3.5 mr-1" />
                  PDF
                </Button>
                <Button 
                  variant="forest" 
                  size="sm" 
                  className="flex-1 text-xs h-8 sm:h-9"
                  onClick={() => exportToExcel(report.title)}
                >
                  <Download className="w-3.5 h-3.5 mr-1" />
                  Excel
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Downloads - Cleaned up (no mock entries) */}
      <Card variant="elevated">
        <CardHeader className="p-4 sm:p-6 pb-2 sm:pb-4">
          <CardTitle className="text-base sm:text-lg">Recent Downloads</CardTitle>
          <CardDescription className="text-xs sm:text-sm">
            Exported reports will appear here
          </CardDescription>
        </CardHeader>
        <CardContent className="p-4 sm:p-6 pt-0">
          <div className="text-center py-8 text-muted-foreground">
            <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p className="text-sm">No downloads yet</p>
            <p className="text-xs mt-1">Generate a report to see it here</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
