// src/components/reports/Reports.tsx
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  FileText, 
  Download, 
  Users, 
  ShoppingCart, 
  Tractor, 
  GraduationCap, 
  TrendingUp,
  Calendar,
  Building2
} from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable'; // Important: enables tables
import { utils, writeFile } from 'xlsx';
import { format } from 'date-fns';

const reportTypes = [
  { id: 'sales', title: 'Sales Report', description: 'Sales transactions, revenue, and commissions', icon: ShoppingCart, color: 'forest' },
  { id: 'farmers', title: 'Farmer Profiles', description: 'Farmer registry with contact details', icon: Users, color: 'wheat' },
  { id: 'mechanisation', title: 'Mechanisation Report', description: 'Machinery service bookings summary', icon: Tractor, color: 'earth' },
  { id: 'trainings', title: 'Training Report', description: 'Capacity building and attendance', icon: GraduationCap, color: 'forest' },
  { id: 'performance', title: 'Performance Report', description: 'TOT metrics and targets achieved', icon: TrendingUp, color: 'wheat' },
  { id: 'commission', title: 'Commission Report', description: 'Commission earnings breakdown', icon: FileText, color: 'earth' },
];

const managerReports = [
  { id: 'branch', title: 'Branch Performance', description: 'Branch-level analytics', icon: Building2, color: 'forest' },
  { id: 'tot-comparison', title: 'TOT Comparison', description: 'Compare all TOTs in branch', icon: Users, color: 'wheat' },
];

export function Reports() {
  const { user } = useAuth();
  const currentDate = format(new Date(), 'PPP'); // e.g., "December 24, 2025"
  const currentMonth = format(new Date(), 'MMMM yyyy');

  const allReports = user?.role === 'manager' || user?.role === 'admin' 
    ? [...reportTypes, ...managerReports] 
    : reportTypes;

  const getColorClass = (color: string) => {
    switch (color) {
      case 'forest': return 'bg-primary text-primary-foreground';
      case 'wheat': return 'bg-accent text-accent-foreground';
      case 'earth': return 'bg-secondary text-secondary-foreground';
      default: return 'bg-muted text-foreground';
    }
  };

  // Placeholder empty data (will be replaced by API later)
  const emptyRows = [
    { label: 'No data available', value: '-' },
  ];

  const exportToPDF = (title: string) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text(title, 20, 20);
    doc.setFontSize(12);
    doc.text(`Generated on: ${currentDate}`, 20, 30);
    doc.text(`Generated by: ${user?.name || 'System User'}`, 20, 38);

    // Empty state message
    doc.setFontSize(14);
    doc.text('No data available at this time', 20, 60);
    doc.setFontSize(11);
    doc.text('Connect your backend API to populate real report data.', 20, 70);
    doc.text('This template will automatically fill with live data when ready.', 20, 80);

    // Footer
    doc.setFontSize(10);
    doc.text('MR Dashboard • Confidential', 20, 280);

    doc.save(`${title.replace(/\s+/g, '_')}_${currentMonth}.pdf`);
  };

  const exportToExcel = (title: string) => {
    const ws = utils.aoa_to_sheet([
      [title],
      [`Generated on: ${currentDate}`],
      [`Generated by: ${user?.name || 'System User'}`],
      [], // empty row
      ['Status', 'Message'],
      ['Info', 'No data available at this time'],
      ['', 'Connect backend API for live data'],
    ]);

    const wb = utils.book_new();
    utils.book_append_sheet(wb, ws, 'Report');
    
    writeFile(wb, `${title.replace(/\s+/g, '_')}_${currentMonth}.xlsx`);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
        <div>
          <h1 className="font-heading text-xl sm:text-2xl font-bold text-foreground">Reports</h1>
          <p className="text-sm text-muted-foreground">Generate and export reports in PDF or Excel</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" disabled>
            <Calendar className="w-4 h-4 mr-2" />
            <span className="hidden sm:inline">Select </span>Date Range
          </Button>
        </div>
      </div>

      {/* Monthly Summary */}
      <Card variant="gradient" className="p-4 sm:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h3 className="font-heading text-base sm:text-lg font-semibold mb-1">Monthly Summary</h3>
            <p className="text-xs sm:text-sm opacity-80">{currentMonth} overview</p>
          </div>
          <div className="text-center text-muted-foreground">
            <p className="text-sm italic">No data available</p>
            <p className="text-xs mt-1">Live metrics will appear when API is connected</p>
          </div>
        </div>
      </Card>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4">
        {allReports.map((report, index) => (
          <Card 
            key={report.id}
            variant="elevated"
            className="animate-fade-in"
            style={{ animationDelay: `${index * 0.05}s` }}
          >
            <CardHeader className="pb-2 p-4 sm:p-6 sm:pb-2">
              <div className="flex items-start justify-between gap-2">
                <div className={`w-10 h-10 sm:w-12 sm:h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${getColorClass(report.color)}`}>
                  <report.icon className="w-5 h-5 sm:w-6 sm:h-6" />
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">PDF</Badge>
                  <Badge variant="outline" className="text-xs">Excel</Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-4 sm:p-6 pt-2 sm:pt-2">
              <CardTitle className="text-sm sm:text-lg mb-1">{report.title}</CardTitle>
              <CardDescription className="text-xs sm:text-sm mb-3 sm:mb-4 line-clamp-2">
                {report.description}
              </CardDescription>
              <div className="flex gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="flex-1 text-xs h-8 sm:h-9"
                  onClick={() => exportToPDF(report.title)}
                >
                  <Download className="w-3.5 h-3.5 mr-1" />
                  PDF
                </Button>
                <Button 
                  variant="forest" 
                  size="sm" 
                  className="flex-1 text-xs h-8 sm:h-9"
                  onClick={() => exportToExcel(report.title)}
                >
                  <Download className="w-3.5 h-3.5 mr-1" />
                  Excel
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Downloads */}
      <Card variant="elevated">
        <CardHeader className="p-4 sm:p-6 pb-2 sm:pb-4">
          <CardTitle className="text-base sm:text-lg">Recent Downloads</CardTitle>
          <CardDescription className="text-xs sm:text-sm">
            Your exported reports will appear here
          </CardDescription>
        </CardHeader>
        <CardContent className="p-4 sm:p-6 pt-0">
          <div className="text-center py-12 text-muted-foreground">
            <FileText className="w-16 h-16 mx-auto mb-4 opacity-40" />
            <p className="text-base font-medium">No reports exported yet</p>
            <p className="text-sm mt-2">Click PDF or Excel above to generate one</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
